export const tags = ["campeonatos", "jogadores", "jogos completos"];

export const videoLinks = [
  {
    id: 1,
    title: "Este é o título para o primeiro vídeo lançado",
    link: "https://www.youtube.com/embed/JVJHaefHPZ0",
    image: "https://img.youtube.com/vi/JVJHaefHPZ0/maxresdefault.jpg",
    tags: [tags[0], tags[2]],
  },
  {
    id: 2,
    title: "Este é o título para todos",
    link: "https://www.youtube.com/embed/5ijgvM4XNW0",
    image: "https://img.youtube.com/vi/5ijgvM4XNW0/maxresdefault.jpg",
    tags: [tags[0], tags[2]],
  },
  {
    id: 3,
    title: "Este é o título para todos",
    link: "https://www.youtube.com/embed/T09xdwPSqIQ",
    image: "https://img.youtube.com/vi/T09xdwPSqIQ/maxresdefault.jpg",
    tags: [tags[0], tags[2]],
  },
  {
    id: 4,
    title: "Este é o título para todos",
    link: "https://www.youtube.com/embed/GJ8Vm-h0V8I",
    image: "https://img.youtube.com/vi/GJ8Vm-h0V8I/maxresdefault.jpg",
    tags: [tags[0], tags[2]],
  },
  {
    id: 5,
    title: "Este é o título para todos",
    link: "https://www.youtube.com/embed/GJ8Vm-h0V8I",
    image: "https://img.youtube.com/vi/GJ8Vm-h0V8I/maxresdefault.jpg",
    tags: [tags[0], tags[2]],
  },
  {
    id: 6,
    title: "Este é o título para todos",
    link: "https://www.youtube.com/embed/T09xdwPSqIQ",
    image: "https://img.youtube.com/vi/T09xdwPSqIQ/maxresdefault.jpg",
    tags: [tags[0], tags[2]],
  },
  {
    id: 7,
    title: "Este é o título para todos",
    link: "https://www.youtube.com/embed/5ijgvM4XNW0",
    image: "https://img.youtube.com/vi/5ijgvM4XNW0/maxresdefault.jpg",
    tags: [tags[0], tags[2]],
  },
  {
    id: 8,
    title: "Este é o título para todos",
    link: "https://www.youtube.com/embed/9U3IhLAnSxM",
    image: "https://img.youtube.com/vi/9U3IhLAnSxM/maxresdefault.jpg",
    tags: [tags[0], tags[2]],
  },
  {
    id: 9,
    title: "Este é o título para todos",
    link: "https://google.com",
    image: "https://img.youtube.com/vi/ysz5S6PUM-U/maxresdefault.jpg",
    tags: [tags[0], tags[2]],
  },
  {
    id: 10,
    title: "Este é o título para todos",
    link: "https://google.com",
    image: "https://img.youtube.com/vi/ysz5S6PUM-U/maxresdefault.jpg",
    tags: [tags[0], tags[2]],
  },
  {
    id: 11,
    title: "Este é o título para todos",
    link: "https://google.com",
    image: "https://img.youtube.com/vi/ysz5S6PUM-U/maxresdefault.jpg",
    tags: [tags[0], tags[2]],
  },
  {
    id: 12,
    title: "Este é o título para todos",
    link: "https://google.com",
    image: "https://img.youtube.com/vi/ysz5S6PUM-U/maxresdefault.jpg",
    tags: [tags[0], tags[2]],
  },
  {
    id: 13,
    title: "Todos os gols de Roberto Carlos pelo Corinthians",
    link: "https://www.youtube.com/embed/dNNhtVkciI4",
    image: "https://i3.ytimg.com/vi/dNNhtVkciI4/maxresdefault.jpg",
    tags: [tags[0], tags[2]],
  },
  {
    id: 14,
    title: "Todos os gols de Emerson Sheik pelo Corinthians",
    link: "https://www.youtube.com/embed/XzMTW9k_fc8",
    image: "https://i3.ytimg.com/vi/XzMTW9k_fc8/maxresdefault.jpg",
    tags: [tags[0], tags[2]],
  },
  {
    id: 15,
    title: "Todos os gols de Rincon pelo Corinthians",
    link: "https://www.youtube.com/embed/OlgRFX0HCIs",
    image: "https://img.youtube.com/vi/OlgRFX0HCIs/maxresdefault.jpg",
    tags: [tags[0], tags[2]],
  },
  {
    id: 16,
    title: "Todos os gols de Ronaldo pelo Corinthians",
    link: "https://www.youtube.com/embed/t4UoNvaVMlU",
    image: "https://i3.ytimg.com/vi/wpGc2wvbc8U/maxresdefault.jpg",
    tags: [tags[0], tags[2]],
  },
  {
    id: 17,
    title: "Todos os gols de Carlos Tevez pelo Corinthians",
    link: "https://www.youtube.com/embed/wxUdfYew3q0",
    image: "https://i3.ytimg.com/vi/wxUdfYew3q0/maxresdefault.jpg",
    tags: [tags[1]],
  },
  {
    id: 18,
    title: "Todos os gols de Rodriguinho pelo Corinthians",
    link: "https://www.youtube.com/embed/YyCa9hWPukY",
    image: "https://i3.ytimg.com/vi/YyCa9hWPukY/maxresdefault.jpg",
    tags: [tags[1]],
  },
  {
    id: 19,
    title: "Todos os gols de Douglas pelo Corinthians",
    link: "https://www.youtube.com/embed/24pa2wMGPrs",
    image: "https://i3.ytimg.com/vi/24pa2wMGPrs/maxresdefault.jpg",
    tags: [tags[1]],
  },
  {
    id: 20,
    title: "Todos os gols de Ralf pelo Corinthians",
    link: "https://www.youtube.com/embed/GlLCpceGJ1c",
    image: "https://i3.ytimg.com/vi/GlLCpceGJ1c/maxresdefault.jpg",
    tags: [tags[1]],
  },
  {
    id: 21,
    title: "Todos os gols de Nilmar pelo Corinthians",
    link: "https://www.youtube.com/embed/HeY9pYMK1f8",
    image: "https://i3.ytimg.com/vi/HeY9pYMK1f8/maxresdefault.jpg",
    tags: [tags[1]],
  },
  {
    id: 22,
    title: "Todos os gols de Liedson pelo Corinthians",
    link: "https://www.youtube.com/embed/CTfMC5pB59I",
    image: "https://i3.ytimg.com/vi/CTfMC5pB59I/maxresdefault.jpg",
    tags: [tags[1]],
  },
  {
    id: 23,
    title: "Todos os gols de Vampeta pelo Corinthians",
    link: "https://www.youtube.com/embed/paMfIHqS2_g",
    image: "https://i3.ytimg.com/vi/paMfIHqS2_g/maxresdefault.jpg",
    tags: [tags[1]],
  },
  {
    id: 24,
    title: "Todos os gols de Romarinho pelo Corinthians",
    link: "https://www.youtube.com/embed/IlecQ7hy3OU",
    image: "https://i3.ytimg.com/vi/IlecQ7hy3OU/maxresdefault.jpg",
    tags: [tags[1]],
  },
  {
    id: 25,
    title: "Todos os gols de Danilo pelo Corinthians",
    link: "https://www.youtube.com/embed/3Ad7sJeyh8g",
    image: "https://i3.ytimg.com/vi/3Ad7sJeyh8g/maxresdefault.jpg",
    tags: [tags[1]],
  },
  {
    id: 26,
    title: "Todos os gols de Paulinho pelo Corinthians",
    link: "https://www.youtube.com/embed/JYNkyJxCqa8",
    image: "https://i3.ytimg.com/vi/JYNkyJxCqa8/maxresdefault.jpg",
    tags: [tags[1]],
  },
  {
    id: 27,
    title: "Todos os gols de Romero pelo Corinthians",
    link: "https://www.youtube.com/embed/bB56eP4nSBw",
    image: "https://i3.ytimg.com/vi/bB56eP4nSBw/maxresdefault.jpg",
    tags: [tags[1]],
  },
  {
    id: 28,
    title: "Todos os gols de Dentinho pelo Corinthians",
    link: "https://www.youtube.com/embed/cm1qkHr2GjY",
    image: "https://i3.ytimg.com/vi/cm1qkHr2GjY/maxresdefault.jpg",
    tags: [tags[1]],
  },
  {
    id: 29,
    title: "Todos os gols de Cristian pelo Corinthians",
    link: "https://www.youtube.com/embed/3dWFKKB5pOQ",
    image: "https://i3.ytimg.com/vi/3dWFKKB5pOQ/maxresdefault.jpg",
    tags: [tags[1]],
  },
  {
    id: 30,
    title: "Todos os gols de Elias pelo Corinthians",
    link: "https://www.youtube.com/embed/1tVsj0hGq1w",
    image: "https://i3.ytimg.com/vi/1tVsj0hGq1w/maxresdefault.jpg",
    tags: [tags[1]],
  },
  {
    id: 31,
    title: "Todos os gols de Renato Augusto pelo Corinthians",
    link: "https://www.youtube.com/embed/yB2DNj-VduA",
    image: "https://i3.ytimg.com/vi/yB2DNj-VduA/maxresdefault.jpg",
    tags: [tags[1]],
  },
  {
    id: 32,
    title: "Todos os gols de Willian pelo Corinthians",
    link: "https://www.youtube.com/embed/b6MuUWWmWjI",
    image: "https://i3.ytimg.com/vi/b6MuUWWmWjI/maxresdefault.jpg",
    tags: [tags[1]],
  },
  {
    id: 33,
    title: "Todos os gols de Kleber pelo Corinthians",
    link: "https://www.youtube.com/embed/zL4k8Qxeui8",
    image: "https://i3.ytimg.com/vi/zL4k8Qxeui8/maxresdefault.jpg",
    tags: [tags[1]],
  },
  {
    id: 34,
    title: "Todos os gols de Rogerio pelo Corinthians",
    link: "https://www.youtube.com/embed/QZf24VQcRzw",
    image: "https://i3.ytimg.com/vi/QZf24VQcRzw/maxresdefault.jpg",
    tags: [tags[1]],
  },
  {
    id: 35,
    title: "Todos os gols de Luizão pelo Corinthians",
    link: "https://www.youtube.com/embed/WD7ZNusBqBo",
    image: "https://i3.ytimg.com/vi/WD7ZNusBqBo/maxresdefault.jpg",
    tags: [tags[1]],
  },
  {
    id: 36,
    title: "Todos os gols de Jadson pelo Corinthians na primeira passagem",
    link: "https://www.youtube.com/embed/mXalg4nmf0c",
    image: "https://i3.ytimg.com/vi/mXalg4nmf0c/maxresdefault.jpg",
    tags: [tags[1]],
  },
  {
    id: 37,
    title: "Todos os gols de Jadson pelo Corinthians na segunda passagem",
    link: "https://www.youtube.com/embed/rX3atNyZ5pc",
    image: "https://i3.ytimg.com/vi/rX3atNyZ5pc/maxresdefault.jpg",
    tags: [tags[2]],
  },
  {
    id: 38,
    title: "Todos os gols de Chicão pelo Corinthians",
    link: "https://www.youtube.com/embed/0NIC8ZWpysA",
    image: "https://i3.ytimg.com/vi/0NIC8ZWpysA/maxresdefault.jpg",
    tags: [tags[2]],
  },
  {
    id: 39,
    title: "Todos os gols de Fabio Santos pelo Corinthians",
    link: "https://www.youtube.com/embed/QsoaIqc1t3o",
    image: "https://i3.ytimg.com/vi/QsoaIqc1t3o/maxresdefault.jpg",
    tags: [tags[2]],
  },
  {
    id: 40,
    title: "Todos os gols de Carlos Gamarra pelo Corinthians",
    link: "https://www.youtube.com/embed/gdCgod2NTJk",
    image: "https://i3.ytimg.com/vi/gdCgod2NTJk/maxresdefault.jpg",
    tags: [tags[2]],
  },
  {
    id: 41,
    title: "Todos os gols de Gilmar Fuba pelo Corinthians",
    link: "https://www.youtube.com/embed/jmFNSnZyrs8",
    image: "https://i3.ytimg.com/vi/jmFNSnZyrs8/maxresdefault.jpg",
    tags: [tags[2]],
  },
  {
    id: 42,
    title: "Todos os gols de Paolo Guerrero pelo Corinthians",
    link: "https://www.youtube.com/embed/FAMw_Oa2gWI",
    image: "https://i3.ytimg.com/vi/UC143ci0vbQ/maxresdefault.jpg",
    tags: [tags[2]],
  },
  {
    id: 43,
    title: "Todos os gols de Marcelinho Carioca em 1995",
    link: "https://www.youtube.com/embed/RF4h01BlMx0",
    image: "https://i3.ytimg.com/vi/RF4h01BlMx0/maxresdefault.jpg",
    tags: [tags[2]],
  },
  {
    id: 44,
    title: "Todos os gols de Marcelinho Carioca em 1995",
    link: "https://www.youtube.com/embed/7w3UM4XEixo",
    image: "https://i3.ytimg.com/vi/7w3UM4XEixo/maxresdefault.jpg",
    tags: [tags[2]],
  },
  {
    id: 45,
    title: "Todos os gols de Marcelinho Carioca em 1996",
    link: "https://www.youtube.com/embed/BeXSo9xYJE4",
    image: "https://i3.ytimg.com/vi/BeXSo9xYJE4/maxresdefault.jpg",
    tags: [tags[2]],
  },
  {
    id: 46,
    title: "Todos os gols de Marcelinho Carioca em 1997",
    link: "https://www.youtube.com/embed/zUhTDicxVK8",
    image: "https://i3.ytimg.com/vi/zUhTDicxVK8/maxresdefault.jpg",
    tags: [tags[2]],
  },
  {
    id: 47,
    title: "Todos os gols de Marcelinho Carioca em 1998",
    link: "https://www.youtube.com/embed/CEm9OrboMNc",
    image: "https://i3.ytimg.com/vi/CEm9OrboMNc/maxresdefault.jpg",
    tags: [tags[2]],
  },
  {
    id: 48,
    title: "Todos os gols de Marcelinho Carioca em 1999",
    link: "https://www.youtube.com/embed/GNcfB0FzDBs",
    image: "https://i3.ytimg.com/vi/GNcfB0FzDBs/maxresdefault.jpg",
    tags: [tags[2]],
  },
  {
    id: 49,
    title: "Todos os gols de Marcelinho Carioca em 2000",
    link: "https://www.youtube.com/embed/tkmZcobVO0Y",
    image: "https://i3.ytimg.com/vi/tkmZcobVO0Y/maxresdefault.jpg",
    tags: [tags[2]],
  },
  {
    id: 50,
    title: "Todos os gols de Marcelinho Carioca em 2001",
    link: "https://www.youtube.com/embed/3HNbcPautKY",
    image: "https://i3.ytimg.com/vi/3HNbcPautKY/maxresdefault.jpg",
    tags: [tags[2]],
  },
];
